### ISSUE TITLE
add title for phase and description of phase

### ISSUE THREAD

**Issue by briacht** [bradygaster/downr#23]
When I hit "Phase 1: Getting Started", I'd expect to see the phase name as the title, not just the workshop name. Would also be nice to be able to add a 1-2 sentence description of the phase.

![image](https://user-images.githubusercontent.com/10437687/87985052-d3287700-ca8f-11ea-86d3-986ffb8d6940.png)

**Comment by bradygaster** [comment]
@briacht I made this change and merged it into your content branch, then I merged your latest pr into it as well. I did notice, you've not been updating the `description` metadata element for a lot of the articles. which is actually okay, because you'll want to consider this issue's resolution as you create descriptions for posts now. 

think of the description of an article as the thing that appears on each article's card in both the home page and category views. most of yours (see your screen shot) still say "the first step in setting up a downr workshop is....". Think of each phase's first step's description as "the introduction sentence to the whole phase." 

each phase page will appear as you desired, with that phase's title appearing at the top of the page. also, the **first article in that phase's description** will be used as the description of the phase. 

if that doesn't make sense, ping me and we'll re-think it, but I think the IA of it makes folks think of that first step in a phase **as the introduction to the phase** and it'll force folks to use that step to introduce what the audience will be about to do.
